apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SHreyank4Real/for-personal-k8s.git
    targetRevision: main
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true