apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-resume
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:SHreyank4Real/for-personal-k8s.git
    targetRevision: main
    path: personal-resume
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-resume
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true