replicaCount: 1

name: shreyank-resume

image:
  repository: shreyanksharma
  name: shreyankresume
  pullPolicy: IfNotPresent
  tag: "27-03-2026-732b0ade-1fb6-4d6a-b78c-b10c0ab00129"

imagePullSecrets: []

contianer:
  port: 80
  memoryReq: "32Mi"
  memoryLim: "64Mi"
  cpuReq: "50m"
  cpuLim: "100m"

service:
  type: NodePort
  nodePortPort: 30002

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
