# templates/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.name }}-limitrange
spec:
  limits:
    - type: Pod
      max:
        cpu: {{ .Values.container.cpuLim }}
        memory: {{ .Values.container.memoryLim }}
      min:
        cpu: {{ .Values.container.cpuReq }}
        memory: {{ .Values.container.memoryReq }}
    - type: Container
      default:
        cpu: {{ .Values.container.cpuLim }}
        memory: {{ .Values.container.memoryLim }}
      defaultRequest:
        cpu: {{ .Values.container.cpuReq }}
        memory: {{ .Values.container.memoryReq }}
      max:
        cpu: {{ .Values.container.cpuLim }}
        memory: {{ .Values.container.memoryLim }}
      min:
        cpu: {{ .Values.container.cpuReq }}
        memory: {{ .Values.container.memoryReq }}