apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  type: {{ .Values.service.type }} 
  ports:
    - name: http
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePortPort }} 
      protocol: TCP
  selector:
    app: {{ .Values.name }}